# Use the official Python 3.12.9 slim image
FROM python:3.11.11-slim

RUN apt-get update
RUN apt-get install -y default-jdk
RUN apt-get install -y poppler-utils
RUN apt-get install -y ghostscript
RUN apt-get install -y python3-pip
RUN apt-get install -y tesseract-ocr

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application files
COPY . .

# Command to run the application

CMD ["streamlit", "run", "streamlit_app.py", "--server.port", "8080", "--server.address", "0.0.0.0",  "--server.headless", "true", "--server.runOnSave", "true"]
